# fly.toml app configuration file generated for crimson-pond-3230 on 2023-06-19T21:44:46+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crimson-pond-3230"
primary_region = "ams"

[env]
  PORT = "8080" # add this

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
